derma_track_src/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

"""
URL configuration for app project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("login.urls")),
    path("core/", include("core.urls")),
    path("super_resolution/", include("super_resolution.urls")),
    path("administrator/", include("administrator.urls")),
    path("camera/", include('camera.urls')),
    path("encrypt/", include('image_encryption.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

derma_track_src/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    
    path("patient_profile", views.patient_profile, name = "patient_profile"),
    path("patient_list", views.patient_list, name = "patient_list"),
    path("create_patient/", views.create_patient, name = "create_patient"),
    path("patient_profile/<int:id>/", views.patient_profile, name = "patient_profile"),
    
    path('create_visit/', views.create_visit, name = "create_visit"),
    path('visit_list', views.visit_list, name = 'visit_list'),
    path('visit_status', views.visit_status_change, name = 'visit_status'),
    path('visit_view', views.visit_view, name = "visit_view"),
    path('visit_list/<int:visit_id>/folders/', views.list_visit_folders, name='list_visit_folders'),
    path('visit_list/<int:visit_id>/<str:body_part>/images', views.list_visit_folder_images, name='list_visit_folder_images'),
    path('visit_list/get_image/<int:id>', views.get_image, name='get_image'),
    path('visit_list/get_enchanced_image/<int:id>', views.get_enchanced_image, name='get_enchanced_image'),
    path('visit_list/update_visit_body_part/<int:id>/', views.update_visit_body_part, name = "update_visit_body_part"),
    path('visit_list/get_annotations/<int:id>/', views.get_annotations, name = "get_annotations"),
    path('visit_list/delete_image/<int:id>/', views.delete_image,  name = "delete_image"),
    path('get_visit_by_patient_name/', views.get_visit_by_patient_name, name = "get_visit_by_patient_name"),
    path('get_patient_by_name/', views.get_patient_by_name, name = "get_patient_by_name"),
    path('get_doctor_by_name/', views.get_doctor_by_name, name = "get_doctor_by_name"),
    path('doctor_list', views.doctor_list, name = 'doctor_list')
]

derma_track_src/core/models.py
from django.db import models
from login.models import Doctor
from multiselectfield import MultiSelectField
import os

def get_image_path(instance, filename):
    return os.path.join('visits', f"visit_{str(instance.visit.pk)}", instance.body_part.name, f"image_{instance.pk}", filename)

def get_preview_path(instance, filename):
    return os.path.join('visits', f"visit_{str(instance.visit.pk)}", instance.body_part.name, filename)

def get_super_path(instance, filename):
    return os.path.join('visits', f"visit_{str(instance.visit.pk)}", instance.body_part.name, filename)

class Status(models.TextChoices):
    """
    Enumeration for the status of a visit.
    """
     
    SCHEDULED = 'scheduled', 'Scheduled'
    STARTED   = 'started',   'Started'
    FINISHED  = 'finished',  'Finished'
    CANCELED  = 'canceled',  'Canceled'
    
class BloodGroup(models.TextChoices):
    """
    Enumeration for the blood type.
    """
    A_POSITIVE    = 'A+', 'A Positive'
    A_NEGATIVE    = 'A-', 'A Negative'
    B_POSITIVE    = 'B+', 'B Positive'
    B_NEGATIVE    = 'B-', 'B Negative'
    AB_POSITIVE   = 'AB+', 'AB Positive'
    AB_NEGATIVE   = 'AB-', 'AB Negative'
    O_POSITIVE    = 'O+', 'O Positive'
    O_NEGATIVE    = 'O-', 'O Negative'
    
class Allergy(models.TextChoices):
    """
    Enumeration for the allergies.
    """
    PEANUTS     = 'peanuts', 'Peanuts'
    DAIRY       = 'dairy', 'Dairy'
    GLUTEN      = 'gluten', 'Gluten'
    SHELLFISH   = 'shellfish', 'Shellfish'
    SOY         = 'soy', 'Soy'
    EGGS        = 'eggs', 'Eggs'
    TREE_NUTS   = 'tree_nuts', 'Tree Nuts'
    WHEAT       = 'wheat', 'Wheat'
    FISH        = 'fish', 'Fish'
    SESAME      = 'sesame', 'Sesame'

class Sex(models.TextChoices):
    """
    Enumeration for the Sex.
    """
    MALE    = 'male', 'Male'
    FEMALE  = 'female', 'Female'
    OTHER   = 'other', 'Other'

# Create your models here.
class Patient(models.Model):
    """
    Model representing a patient in the system.

    Attributes:
        national_number (str): National ID number (unique).
        name (str): First name.
        surname (str): Last name.
        date_of_birth (date): Birth date.
        blood_group (str): Blood group from predefined choices.
        allergies (list): Multiple allergies from predefined choices.
        street (str): Address street name.
        number (int): Street number.
        city (str): City.
        zip_code (int): Postal code.
        phone_number (str): Primary contact number.
        other_phone_number (str): Secondary contact number (optional).
    """
    
    national_number = models.CharField(max_length=11, unique=True, blank=False)
    name = models.CharField(max_length=255, blank=False) 
    surname = models.CharField(max_length=255, blank=False)
    date_of_birth = models.DateField(blank=False)
    blood_group = models.CharField(max_length=30, choices=BloodGroup.choices, default=BloodGroup.A_POSITIVE, blank=False)
    allergies = MultiSelectField(choices=Allergy.choices, max_length=200, blank=True, default = None)
    sex = models.CharField(max_length=30, choices=Sex.choices, default=Sex.OTHER, blank=False)
    street = models.CharField(max_length=255, blank=False)
    number = models.IntegerField(blank=False)
    city = models.CharField(max_length=255, blank=False)
    zip_code = models.IntegerField(blank=False)
    phone_number = models.CharField(max_length=255, blank=False)
    other_phone_number = models.CharField(max_length=255, blank=True)

    def __str__(self):
        """
        String representation of the doctor.

        Returns:
            str: Formatted string including id and full name.
        """
        return str(self.pk) + " - " + self.full_name()
    
    def full_name(self):
        """
        Returns the full name of the patient.

        Returns:
            str: Concatenation of name and surname.
        """
        return self.name + " " + self.surname
    
    def full_adress(self):
        """
        Returns the full adress of the patient.

        Returns:
            str: Concatenation of street, number, city and zip code.
        """
        return self.street + " " + str(self.number) + ", " + self.city + " (" + str(self.zip_code) + ")"
    
class Visit(models.Model):
    """
    Model representing a Visit in the system.

    Attributes:
        date (datetime): Date and time of the visit.
        note (str): Optional notes for the visit.
        is_patient_present (bool): Indicates if the patient attended.
        status (str): Visit status from Status choices.
        patient (Patient): Linked patient.
        doctor (Doctor): Linked doctor.
    """
    
    date = models.DateTimeField(blank = False)
    note = models.TextField(blank = True)
    is_patient_present = models.BooleanField(blank = True, default=False)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.SCHEDULED)
    patient = models.ForeignKey(Patient, verbose_name=("patient"), on_delete=models.CASCADE, blank = False)
    doctor = models.ForeignKey(Doctor, verbose_name=("doctor"), on_delete=models.CASCADE, blank = False)
    
    def __str__(self):
        """
        String representation of the doctor.

        Returns:
            str: Formatted string including id, doctor name, patient name and datae.
        """
        return str(self.pk) + " - " + self.doctor.full_name() + " / " + self.patient.full_name() + " - "  + str(self.date)
    
class BodyPart(models.Model):
    """
    Model representing a BodyPart in the system.

    Attributes:
        name (str): The name of the body part (e.g., 'Left Shoulder').
    """

    name = models.CharField(max_length=255)
    
    def __str__(self):
        """
        String representation of the body part.

        Returns:
            str: Formatted string including id and name.
        """
        return str(self.pk) + " - " + self.name
    
class VisitBodyPart(models.Model):
    """
    Model representing a VisitBodyPart in the system.

    Attributes:
        image_path (ImageField): Path to encrypted image.
        image_name (str): Filename of encrypted image.
        image_height (int): Original image height in pixels.
        image_width (int): Original image width in pixels.
        image_preview_path (ImageField): Path to preview image (PNG).
        image_preview_name (str): Filename of preview image.
        image_preview_height (int): Preview height in pixels.
        image_preview_width (int): Preview width in pixels.
        image_super_path (ImageField): Path to enhanced/super-resolved image.
        image_super_name (str): Filename of enhanced image.
        image_super_height (int): Height of enhanced image.
        image_super_width (int): Width of enhanced image.
        multi_image_path (str): Path to folder containing image patch set (if any).
        distance_from_subject (float): Distance from camera to subject.
        focal (float): Focal length used during capture.
        pixel_size (float): Physical pixel size (mm).
        annotations (JSON): Optional annotations (e.g., bounding boxes, comments).
        body_part (BodyPart): Related body part.
        visit (Visit): Related visit.
    """
    
    image_path = models.FileField(upload_to = get_image_path, null = True, blank = True)
    image_name = models.CharField(null = True, blank = True, max_length=255)
    image_height = models.IntegerField(default = 0)
    image_width = models.IntegerField(default = 0)
    image_preview_path = models.FileField(upload_to = get_preview_path, null = True, blank = True)
    image_preview_name = models.CharField(null = True, blank = True, max_length=255)
    image_preview_height = models.IntegerField(default = 0)
    image_preview_width = models.IntegerField(default = 0)
    image_super_path = models.FileField(upload_to = get_super_path, null = True, blank = True)
    image_super_name = models.CharField(null = True, blank = True, max_length=255, default = "")
    image_super_height = models.IntegerField(default = 0)
    image_super_width = models.IntegerField(default = 0)
    multi_image_path = models.CharField(null = True, blank = True, max_length=255, default = "")
    distance_from_subject = models.FloatField(blank = True, null = True)
    focal = models.FloatField(default = 3.543)
    pixel_size = models.FloatField(default = 0.0014)
    annotations = models.JSONField(blank = True, null=True, default = None)
    body_part = models.ForeignKey(BodyPart, verbose_name=("body part"), on_delete=models.CASCADE)
    visit = models.ForeignKey(Visit, verbose_name=("visit"), on_delete=models.CASCADE)
    
    def __str__(self):
        """
        String representation of the VisitBodyPart.

        Returns:
            str: Formatted string including ID, visit ID and body part name.
        """
        return str(self.pk) + " - " + "visit_"+str(self.visit.pk) + " - " + self.body_part.name
    

derma_track_src/core/forms.py
from django import forms
from .models import Patient, Visit
from django.utils.timezone import now


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ["national_number", "name", "surname", "date_of_birth", "blood_group", "sex", "allergies", "street", 
                  "number", "city", "zip_code", "phone_number", "other_phone_number"]
        widgets = {
            'date_of_birth': forms.DateInput(attrs={'type': 'date'}),
            'allergies': forms.CheckboxSelectMultiple(),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields["national_number"].widget.attrs.update({"class":"form-control"})
        self.fields["name"].widget.attrs.update({"class":"form-control"})
        self.fields["surname"].widget.attrs.update({"class":"form-control"})
        self.fields["date_of_birth"].widget.attrs.update({"class":"form-control"})
        self.fields["blood_group"].widget.attrs.update({"class":"form-select"})
        self.fields["sex"].widget.attrs.update({"class":"form-select"})
        self.fields["street"].widget.attrs.update({"class":"form-control"})
        self.fields["number"].widget.attrs.update({"class":"form-control"})
        self.fields["city"].widget.attrs.update({"class":"form-control"})
        self.fields["zip_code"].widget.attrs.update({"class":"form-control"})
        self.fields["phone_number"].widget.attrs.update({"class":"form-control"})
        self.fields["other_phone_number"].widget.attrs.update({"class":"form-control"})

class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ['patient', 'date']
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'patient': forms.Select()
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields["patient"].widget.attrs.update({'class': 'form-control selectpicker'})
        self.fields["date"].widget.attrs.update({"class":"form-control", 'min': now().strftime("%Y-%m-%dT%H:%M")})
        
class VisitFormAdmin(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ['patient', 'date', 'doctor']
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'patient': forms.Select(),
            'doctor': forms.Select()
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields["patient"].widget.attrs.update({'class': 'form-control selectpicker'})
        self.fields["doctor"].widget.attrs.update({'class': 'form-control selectpicker'})
        self.fields["date"].widget.attrs.update({"class":"form-control", 'min': now().strftime("%Y-%m-%dT%H:%M")})

derma_track_src/core/templates/partial/doctor_list.html
<div class="container-fluid p-3 bg-light rounded shadow-sm">
    <div class="d-flex gap-2">
        <form class="d-flex flex-grow-1" method ="GET" hx-get="{% url 'get_doctor_by_name' %}" hx-target="#dynamic-body" hx-swap="innerHTML">
            <input type="text" id="search-doctor" name = "name" class="form-control rounded-start" placeholder="Search by Name or Surname...">
            <button type = "submit" class="btn btn-primary">
                <i class="fas fa-search"></i> Search
            </button>
        </form>
    </div>
</div>

<div id = "table" class="container-fluid my-3 p-3 bg-light rounded shadow-sm d-flex flex-column">
    <div class = "table-responsive">
        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Street</th>
                    <th>Number</th>
                    <th>City</th>
                    <th>Zip Code</th>
                    <th>Phone Number</th>
                    <th>Other Phone Number</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for doctor in page.object_list %}
                <tr>
                    <td>{{ doctor.name }}</td>
                    <td>{{ doctor.surname }}</td>
                    <td>{{ doctor.street }}</td>
                    <td>{{ doctor.number }}</td>
                    <td>{{ doctor.city }}</td>
                    <td>{{ doctor.zip_code }}</td>
                    <td>{{ doctor.phone_number }}</td>
                    <td>{{ doctor.other_phone_number }}</td>
                    <td>       
                        <div style="display: flex; align-items: center; gap: 10px;">
                            <form action='doctor' style="margin: 0; display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="id" class="form-control" value="{{ doctor.pk }}" required=""> 
                                <button type="submit" class="btn btn-success" data-mdb-ripple-color="dark" disabled>View</button>
                            </form>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <nav class = "mt-auto">
        <ul class="pagination justify-content-center mt-3">
            <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
                <a class="page-link" 
                   href="#" 
                   {% if page.has_previous %}
                       hx-get="{% url 'doctor_list' %}?page=1" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    &laquo; First
                </a>
            </li>
        
            <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
                <a class="page-link" 
                   href="#"
                   {% if page.has_previous %}
                       hx-get="{% url 'doctor_list' %}?page={{ page.previous_page_number }}" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    Previous
                </a>
            </li>
        
            <li class="page-item active">
                <span class="page-link">
                    Page {{ page.number }} of {{ page.paginator.num_pages }}
                </span>
            </li>
        
            <li class="page-item {% if not page.has_next %}disabled{% endif %}">
                <a class="page-link" 
                   href="#"
                   {% if page.has_next %}
                       hx-get="{% url 'doctor_list' %}?page={{ page.next_page_number }}" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    Next
                </a>
            </li>
        
            <li class="page-item {% if not page.has_next %}disabled{% endif %}">
                <a class="page-link" 
                   href="#"
                   {% if page.has_next %}
                       hx-get="{% url 'doctor_list' %}?page={{ page.paginator.num_pages }}" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    Last &raquo;
                </a>
            </li>
        </ul>        
    </nav>
</div>

derma_track_src/core/templates/partial/visit_form.html
<div class="modal fade" id="mainModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
            
            <form id = "visit-form" method="POST" hx-post="{% url 'create_visit' %}" hx-target="#dynamic-body" hx-swap="innerHTML" onsubmit="dismissModal()">
                {% csrf_token %}

                <div class="modal-header bg-light border-bottom">
                    <h5 class="modal-title">Create New Visit</h5>
                </div>

                <div class="modal-body">

                    {% if  form.doctor %}
                    <div class="mb-3">
                        <label for="id_doctor" class="form-label">Doctor</label>
                        {{ form.doctor }}
                    </div>
                    {% endif %}

                    <div class="mb-3">
                        <label for="id_patient" class="form-label">Patient</label>
                        {{ form.patient }}
                    </div>

                    <div class="mb-3">
                        <label for="id_date" class="form-label">Date and Time</label>
                        {{ form.date }}
                    </div>
                </div>

                <div class="modal-footer border-top">
                    <button type="submit" class="btn btn-primary"> Save</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="clearPopUp()">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

derma_track_src/core/templates/partial/visit_list.html
{% load static %}

<div class="container-fluid p-3 bg-light rounded shadow-sm">
    <div class="d-flex gap-2">
        <form class="d-flex flex-grow-1" method ="GET" hx-get="{% url 'get_visit_by_patient_name' %}" hx-target="#dynamic-body" hx-swap="innerHTML">
            <input type="text" id="search-patient" name = "name" class="form-control rounded-start" placeholder="Search by Name or Surname...">
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-search"></i> Search
            </button>
        </form>
        <form method ="GET" hx-get="{% url 'create_visit' %}" hx-target="#pop-up" hx-swap="innerHTML">
            <button type="submit" class="btn btn-success">
                <i class="fas fa-user-plus"></i> Add Visit
            </button>
        </form>
    </div>
</div>

<div id = "table" class="container-fluid my-3 p-3 bg-light rounded shadow-sm d-flex flex-column">
    <div class = "table-responsive">
        <table class="table align-middle mb-0 bg-white" id="visit-table">
            <thead class="bg-light">
                <tr>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Doctor Name</th>
                    <th>Patient Name</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for visit in page.object_list %}
                <tr>
                    <td>{{ visit.date|date:"l d F Y"}}</td>
                    <td>{{ visit.date|time:"H:i" }}</td>
                    <td>{{ visit.doctor.full_name }}</td>
                    <td class="patient-name">{{ visit.patient.full_name }}</td>
                    <td> 
                        {% if visit.status == "scheduled" %}
                        <span class="badge text-bg-warning">
                        {% elif visit.status == "started" %}
                        <span class="badge text-bg-info">
                        {% elif visit.status == "canceled" %}
                        <span class="badge text-bg-danger">
                        {% else %}
                        <span class="badge text-bg-success">
                        {% endif %}
                        {{ visit.get_status_display  }}
                        </span>
                    </td>
                    <td>       
                        <div style="display: flex; align-items: center; gap: 10px;">
                            {% if visit.status == "canceled" or visit.status == "finished" or visit.status == "started" %}
                            <form class="button-form" hx-post="{% url 'visit_view' %}" hx-target="#pop-up" hx-swap="innerHTML" method='POST'>
                                {% csrf_token %}
                                <input type="hidden" name="id" class="form-control" value="{{visit.pk}}" required=""> 
                                <button type="submit" class="btn btn-success" data-mdb-ripple-color="dark"> View </button>
                            </form>
                            {% endif %}

                            <form class="button-form" hx-post="{% url 'visit_status' %}" hx-target="#dynamic-body" hx-swap="innerHTML" method='POST'>
                                {% csrf_token %}
                                <input type="hidden" name="id" class="form-control" value="{{visit.pk}}" required=""> 
                                {% if visit.status == "scheduled" %}
                                    <button type="submit" class="btn btn-success" value="Started" name="status" data-mdb-ripple-color="dark"> Start </button>
                                    <button type="submit" class="btn btn-danger" value="Canceled" name="status" data-mdb-ripple-color="dark"> Cancel </button>
                                {% elif visit.status == "started" %}
                                    <button type="submit" class="btn btn-danger" value="Finished" name="status" data-mdb-ripple-color="dark"> Finish </button>
                                {% endif %}
                            </form>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <nav class = "mt-auto">
        <ul class="pagination justify-content-center mt-3">
            <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
                <a class="page-link" 
                   href="#" 
                   {% if page.has_previous %}
                       hx-get="{% url 'visit_list' %}?page=1" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    &laquo; First
                </a>
            </li>
        
            <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
                <a class="page-link" 
                   href="#"
                   {% if page.has_previous %}
                       hx-get="{% url 'visit_list' %}?page={{ page.previous_page_number }}" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    Previous
                </a>
            </li>
        
            <li class="page-item active">
                <span class="page-link">
                    Page {{ page.number }} of {{ page.paginator.num_pages }}
                </span>
            </li>
        
            <li class="page-item {% if not page.has_next %}disabled{% endif %}">
                <a class="page-link" 
                   href="#"
                   {% if page.has_next %}
                       hx-get="{% url 'visit_list' %}?page={{ page.next_page_number }}" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    Next
                </a>
            </li>
        
            <li class="page-item {% if not page.has_next %}disabled{% endif %}">
                <a class="page-link" 
                   href="#"
                   {% if page.has_next %}
                       hx-get="{% url 'visit_list' %}?page={{ page.paginator.num_pages }}" 
                       hx-target="#dynamic-body" 
                       hx-swap="innerHTML"
                   {% endif %}
                >
                    Last &raquo;
                </a>
            </li>
        </ul> 
    </nav>
</div>

<div id="pop-up"></div>